name: "update-project-item-fields"
description: "Updates the project item fields by project item ID"
author: "KekeHub"
inputs:
  app-installation-id:
    required: false
    description: "GitHub App installation ID"

  app-integration-id:
    required: false
    description: "GitHub App integration ID a.k.a app ID"

  app-private-key:
    required: false
    description: "GitHub App private key"

  fields:
    required: false
    description: "Fields to update in Key value format"

  owner:
    required: false
    description: "Owner (organization ID) of the project owner"
    default: ${{ github.repository_owner }}

  project-item-id:
    required: true
    description: "ID of the project item"

  token:
    required: false
    description: "Credential to access to the repo to post the comment"
    default: ${{ github.token }}

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "archive"
  color: "orange"
